enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "mininxd/revanced-patches"
rv-brand = "ReVanced Extended"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='yt.rvx' "
version = "auto"                
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"
arch = "both"

[Music]
build-mode = "module"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='ytm.rvx' "
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
arch = "both"
